version: '3'
services:
    degrees-backend:
        image: degrees-backend
        build: ./degrees-backend
        ports: 
            - 3000:3000
    degrees-frontend: 
        image: degrees-frontend
        build: ./degrees-frontend
        ports:
            - 8000:8000
        links:
            - degrees-backend