version: '3'
services:
    degrees-backend:
        image: sonamdo/degrees-backend
        build: .
        ports: 
            - 3000:3000
    degrees-frontend: 
        image: sonamdo/degrees-frontend
        build: .
        ports:
            - 8000:8000
        links:
            - degrees-backend